import './assets/img/Vans';
export const products = [
  {
    id: 1,
    img: './assets/img/Vans/1.jpeg',
    title: 'Vans Old Skool Gumsole',
    brand: 'Vans',
    price: 95,
    desc: 'Inspired by Vans Classic Old Skool, the Ward is a low top, vulcanized lace up style with Vans signature side stripe, a round toe, padded collar for extra comfort, a smooth Lining and a cushioning insole.',
  },
  {
    id: 2,
    img: './assets/img/Vans/2.jpeg',
    title: 'Vans Classic Slip-On',
    brand: 'Vans',
    price: 90,
    desc: 'The low-profile Slip-On canvas offers unbeatable convenience, while the clean design makes Vans White Slip-On shoes the perfect choice for anyone with places to go and things to do.',
  },
  {
    id: 3,
    img: './assets/img/Vans/3.jpeg',
    title: 'Vans Sk8-Hi Suede',
    brand: 'Vans',
    price: 127,
    desc: 'The Sk8-Hi was introduced in 1978 as Style 38, and showcased the now iconic Vans Sidestripe on a new, innovative high top silhouette.',
  },
  {
    id: 4,
    img: './assets/img/Vans/4.jpeg',
    title: 'Vans Sk8-Low',
    brand: 'Vans',
    price: 95,
    desc: 'The Sk8-Low, a takedown of the legendary Vans high top shoe, is built with an array of colors and materials to provide a familiar Sk8-Hi aesthetic in a low top shoe.',
  },
  {
    id: 5,
    img: './assets/img/Vans/5.jpeg',
    title: 'Vans Old Skool Trainers',
    brand: 'Vans',
    price: 105,
    desc: 'Constructed with durable suede and canvas uppers in a range of fresh colorways.',
  },
  {
    id: 6,
    img: './assets/img/Nike/1.jpeg',
    title: 'Nike Running React Miler 2',
    brand: 'Nike',
    price: 130,
    desc: 'An intuitive, lightweight, and well-cushioned design, the swoosh brand updates these shoes with the trust needed to keep going.',
  },
  {
    id: 7,
    img: './assets/img/Nike/2.jpeg',
    title: 'Nike Air Max 270',
    brand: 'Nike',
    price: 140,
    desc: `Nike's first lifestyle Air Max brings you style, comfort and big attitude in the Nike Air Max 270.`,
  },
  {
    id: 8,
    img: './assets/img/Nike/3.jpeg',
    title: `Nike Blazer Mid '77 Vintage`,
    brand: 'Nike',
    price: 125,
    desc: `In the '70s, Nike was the new shoe on the block. So new in fact, we were still breaking into the basketball scene and testing prototypes on the feet of our local team.`,
  },
  {
    id: 9,
    img: './assets/img/Nike/4.jpeg',
    title: 'Nike VaporMax 2021 Flyknit',
    brand: 'Nike',
    price: 250,
    desc: 'Made from at least 20% recycled material by weight, this easy-to-wear design features a stretchy Flyknit upper with a soft, seamless collar.',
  },
  {
    id: 10,
    img: './assets/img/Nike/5.jpeg',
    title: `Nike Blazer Mid '77 Jumbo`,
    brand: 'Nike',
    price: 130,
    desc: 'Harnessing the old-school look you love, it now has an elastic heel with corduroy-like texture and large pull tabs for easy on and off.',
  },
  {
    id: 11,
    img: './assets/img/Adidas/1.jpeg',
    title: 'Adidas Originals Handball Spezial',
    brand: 'Adidas',
    price: 127,
    desc: 'This version is built with a nubuck suede upper for a supple feel. A soft gum rubber outsole keeps them true to their vintage roots.',
  },
  {
    id: 12,
    img: './assets/img/Adidas/2.jpeg',
    title: 'Adidas Originals Gazelle',
    brand: 'Adidas',
    price: 119,
    desc: 'The Gazelle shoe started life as a soccer shoe and grew into an iconic streetwear staple.',
  },
  {
    id: 13,
    img: './assets/img/Adidas/3.jpeg',
    title: 'Adidas Originals NMD V3',
    brand: 'Adidas',
    price: 205,
    desc: `Plush BOOST cushioning means that comfort isn't even a question, and that every step is meant to feel good.`,
  },
  {
    id: 14,
    img: './assets/img/Adidas/4.jpeg',
    title: 'Adidas Originals Niteball II',
    brand: 'Adidas',
    price: 158,
    desc: 'When the sun drops is when the game begins. Crush it on the basketball court and then head out in these adidas Niteball 2.0 Shoes.',
  },
  {
    id: 15,
    img: './assets/img/Adidas/5.jpeg',
    title: 'Adidas Originals Sunshine',
    brand: 'Adidas',
    price: 135,
    desc: 'Add a little sunshine to your look. These adidas shoes are as bright and vibrant as the state they represent.',
  },
  {
    id: 16,
    img: './assets/img/NewBalance/1.jpeg',
    title: 'New Balance 530',
    brand: 'New Balance',
    price: 158,
    desc: 'This casual kick combines everyday style with modern technology like ABZORB cushioning that adds superior comfort underfoot.',
  },
  {
    id: 17,
    img: './assets/img/NewBalance/2.jpeg',
    title: 'New Balance 608',
    brand: 'New Balance',
    price: 125,
    desc: 'Our classic trainer features super-soft cushioning and a durable rubber outsole to deliver the support and comfort your feet need on a daily basis.',
  },
  {
    id: 18,
    img: './assets/img/NewBalance/3.jpeg',
    title: 'New Balance 373',
    brand: 'New Balance',
    price: 133,
    desc: 'The 373 is your new go-anywhere shoe, perfect for the front of your everyday line-up.',
  },
  {
    id: 19,
    img: './assets/img/NewBalance/4.jpeg',
    title: 'New Balance 574',
    brand: 'New Balance',
    price: 158,
    desc: 'The 574 was built to be a reliable shoe that could do a lot of different things well rather than as a platform for revolutionary technology, or as a premium materials showcase.',
  },
  {
    id: 20,
    img: './assets/img/NewBalance/5.jpeg',
    title: 'New Balance Hierro',
    brand: 'New Balance',
    price: 215,
    desc: 'The Fresh Foam X Hierro v7 employs a Vibram® Megagrip outsole to create a protective shell of durability and traction.',
  },
];
